### ISSUE TITLE
Create a C++ Hello, World

### ISSUE THREAD

**Issue by PolymorphiK** [PolymorphiK/git-demo#10]
**Is your feature request related to a problem? Please describe.**
We do not have a C++ program that displays _Hello, World_.

**Describe the solution you'd like**
A C++ program named _program_ that displays _Hello World_.

**Describe alternatives you've considered**
Java, C#

**Additional context**
Ensure you do not use the global namespacing.

**Comment by Qhpadgham** [comment]
Should the program display _Hello, World_ or _Hello World_ ?
